#PBS -j oe  
#PBS -l mppwidth=24 
#PBS -l walltime=00:10:00 
#PBS -N COGENT_job 
#PBS -o /global/homes/c/creyn/code/test/
#PBS -q debug 
#PBS -w /global/homes/c/creyn/code/test/

cd $PBS_O_WORKDIR  
echo "running $0"
echo "cwd is" `pwd`
echo "calling aprun"
aprun -n 24 /global/project/projectdirs/atom/atom-install-edison/cogent/COGENT/exec/cogent.Linux.64.CC.ftn.OPT.MPI.ex $COGENT_PARM_FILE $COGENT_COEFF_FILE $COGENT_GRID_FILE
echo "called aprun"
echo "end $0"
